### ISSUE TITLE
Proxy / X-Forwarded-For support

### ISSUE THREAD

**Issue by markstos** [tunnckoCore/express-ip-filter#6]
Are proxies support or the X-Forward-For header?

When a request comes through a proxy, the req.ip will belong to the proxy and the originating IP will be in the X-Forwarded-For header.

From reading the code and docs, I don't see any mention of this.

It would be possible to chain this with another middleware that makes sure that req.ip is set to the original IP and not a proxy before this middleware runs. If that's the recommended approach, it would be helpful to document it.

**Comment by tunnckoCore** [comment]
Hm, didn't thought for this but sounds easy to implement here.

**Comment by tunnckoCore** [comment]
Actually, u can pass options.id as function. It is passed with req and res, so u can get the x-forwarded-for header and return it. So it will be used instead of the req.ip and passed to the ip-filter package.

Let me know if something more is needed to help you.

**Comment by markstos** [comment]
@tunnckoCore Thanks for the prompt response. It's good to hear there's an option to get the IP from a different source.

The best solution may be to let another module handle setting `req.ip`, so this module can stay focused on whitelisting. The [req-ip](https://github.com/bendrucker/req-ip) module does just this, but it currently has a big flaw: It only handles one left of proxy, when two or more levels are likely.   I opened a [bug report](https://github.com/bendrucker/req-ip/issues/1) about that.

Whether the issue is addressed internally or externally, some guidance in the documentation here would be helpful to remind people that additional steps are required when connections will be arriving through a proxy.

**Comment by tunnckoCore** [comment]
in anyway, the only thing is to pass a function here, so we dont need to do anything here

**Comment by markstos** [comment]
Some guidance in the documentation here would still be helpful to remind people that additional steps are required when connections will be arriving through a proxy, such has chaining this with the [req-ip](https://github.com/bendrucker/req-ip) module.

**Comment by tunnckoCore** [comment]
I don't know what to do more, there is docs for the options so one just need to read the readme. Sorry if this sounds somehow.
PRs are welcome anyway, I would never be against do s upgrades.

Probably one more example using reqIP() passed to the options.id
